### ISSUE TITLE
Comparison to signal-exit

### ISSUE THREAD

**Issue by papb** [sindresorhus/exit-hook#14]
Hello! I found this package and also [signal-exit](https://github.com/tapjs/signal-exit). Is there any practical difference?

I noticed you [use signal-exit instead of this package](https://github.com/sindresorhus/loud-rejection/blob/63acebc25e18516741b7328f4919922b529f8f69/index.js#L3) in another of your modules (loud-rejection).

Thank you!

**Comment by sindresorhus** [comment]
`signal-exit` is more comprehensive. It patches internal events and catches more edge-cases. However, it's also more dangerous and fragile because of this. So I would use `signal-exit` when I need to be absolutely sure something is caught at exit, and this otherwise, which is good enough for most common needs.
